//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭлЖурнал
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int ID_Load { get; set; }
        public Nullable<int> ID_Class { get; set; }
        public Nullable<int> ID_Item { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Item Item { get; set; }
    }
}
