//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭлЖурнал
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int ID_Performance { get; set; }
        public Nullable<int> ID_Item { get; set; }
        public string I_ch { get; set; }
        public string II_ch { get; set; }
        public string III_ch { get; set; }
        public string IV_ch { get; set; }
        public Nullable<int> ID_Student { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Student Student { get; set; }
    }
}
